version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    image: homubee/bookrec-client
    volumes:
      - /usr/src/app/client/node_modules
      - ./client:/usr/src/app/client
  mariadb:
    image: mariadb:10
    ports:
      - 3308:3306
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    restart: always
