services:
    frontend:
        build: frontend
        ports:
            - "80"
        networks:
            - front-tier

    backend:
        build: backend
        expose:
            - "3000"
        networks:
            - front-tier
            - back-tier
        env_file:
            - backend/.env

    database:
        image: mariadb
        expose:
            - "3306"
        networks:
            - back-tier
        volumes:
            - ./db:/var/lib/mysql
        env_file:
            - backend/.env

networks:
    front-tier:
    back-tier:
