services:
    frontend:
        build: ./frontend
        depend_on: backend

    backend:
        build:
            dockerfile: Dockerfile
            context: ./backend
        volumes:

    db:
        image: mariadb:10
        expose:
            - "3306"
        volumes:
        - type: volume
            source: mariadb-data
            target: /var/lib/mysql
        - type: bind
            source: /opt/app/db/conf.d
            target: /etc/mysql/conf.d
        - type: bind
            source: /opt/app/db/docker-entrypoint-initdb.d
            target: /docker-entrypoint-initdb.d
        env_file: .env
        restart: always
