services:
    frontend:
        build: frontend
        ports:
            - "49163:80"
        networks:
            - front-tier

    backend:
        build: backend
        expose:
            - "3000"
        networks:
            - front-tier
            - back-tier
        env_file:
            - backend/.env
        restart: on-failure

    database:
        image: mariadb
        expose:
            - "3306"
        networks:
            - back-tier
        volumes:
            - mariadb-data:/var/lib/mysql
        env_file:
            - backend/.env
        restart: on-failure

networks:
    front-tier:
    back-tier:


volumes:
    mariadb-data:
        external: true
